export default {
  "Амадей 2505": {
    Жаккард: {
      price: 0,
      images: [
        "Carter_Rose.jpg",
        "Gloriya-169A-1.jpg",
        "Gloriya-174A-1.jpg",
        "Gloriya-194A-1.jpg",
        "Gloriya-196A-1.jpg",
        "Gloriya-516A-1.jpg",
        "Gloriya-751A-1.jpg",
        "Monstera-Beige_1b.jpg",
        "Monstera-Black_1A.jpg",
        "Neon 12.jpg",
        "Neon 128.jpg",
        "Neon 131.jpg",
        "Rafaello-213-52_3.jpg",
        "Rafaello-P-10043_1.jpg",
        "Rafaello-P-9883_1.jpg",
        "Tokio_133-36_1.jpg",
        "Tokio_144-35_1.jpg",
        "Tokio_144-36_1.jpg",
        "Viola_200A.jpg",
        "Viola_300a.jpg",
        "Viola_400A.jpg",
        "Viola_501A.jpg",
      ],
    },
    Шенилл: {
      price: 0,
      images: [
        "Akva_110b.jpg",
        "Akva_210a.jpg",
        "Akva_250a.jpg",
        "Akva_370a.jpg",
        "Azaliya_1_5.jpg",
        "Azaliya_2_1.jpg",
        "Azaliya_2_5.jpg",
        "Azaliya_4_5.jpg",
        "Benevento_Jewel.jpg",
        "Benevento_Kornsilk.jpg",
        "Benevento_Moss.jpg",
        "Bryt_white.jpg",
        "Diamond_110C.jpg",
        "Diamond_60C.jpg",
        "Felicia_bordo.jpg",
        "Felicia_green.jpg",
        "Felicia_rose.jpg",
        "Gasmin_16A1.jpg",
        "Gasmin_19A1.jpg",
        "Karolina_15B.jpg",
        "Karolina_16A.jpg",
        "Kelsi_5520_02R.jpg",
        "Kelsi_5520_03R.jpg",
        "Kelsi_5520_05R.jpg",
        "Kelsi_5520_08R.jpg",
        "Kelsi_5520_14R.jpg",
        "Kelsi_5520_66R.jpg",
        "Patricia_200b.jpg",
        "Pozit_Gold.jpg",
        "Pozit_Latte.jpg",
        "Pozit_Mos.jpg",
        "Pozit_Slatte.jpg",
        "Pozitano_bordo.jpg",
        "Shimer_blue.jpg",
        "Shimer_bordo.jpg",
        "Shimer_bronza.jpg",
        "Shimer_payp.jpg",
        "Shimer_salat.jpg",
        "Shimer_strayp.jpg",
        "Siesta_begev.jpg",
        "Siesta_blue.jpg",
        "Silver_Red.jpg",
        "Silver_Stoyn.jpg",
        "Valencia_201C.jpg",
        "Valencia_300B.jpg",
        "Valencia_301B.jpg",
        "Vena white.jpg",
        "Valencia_300C.jpg",
        "Akva_1b.jpg",
        "Аkva_1a.jpg",
      ],
    },
    Экокожа: {
      price: 0,
      backgroundSize: "cover",
      images: [
        "Madras_0515_G.jpg",
        "Madras_1010_Y_20_R.jpg",
        "Madras_1515_Y_40_R.jpg",
        "Madras_20_20_Y50R.jpg",
        "Madras_20_50_Y_20_R.jpg",
        "Madras_6030_R_10_B.jpg",
        "Madras_60_30_70.jpg",
        "Madras_66Q_RED.jpg",
        "Madras_8020_B_90_G.jpg",
        "Madras_8500_N.jpg",
      ],
    },
  },

  "Е1": {
    base: {
      price: 0,
      backgroundSize: "cover",
      images: [
        "Улица.jpg",
        "Сакура.jpg",
        "Орхидея Белая.jpg",
        "Ночной Лондон.jpg",
        "Париж.jpg",
      ],
    },
  },
}

export const FABRICS = [
  /*
  {
    name: "Амадей",
    categories: [
      {
        name: "Жаккард",
        material: "Жаккард",
        count: 37,
      },
      {
        name: "Шинилл",
        material: "Шинилл",
        count: 96,
      },
      {
        name: "Экокожа",
        material: "Экокожа",
        count: 10,
        backgroundSize: "cover",
      },
    ]
  },
  */
  {
    name: "Амадей 2505",
    categories: [
      {
        name: "Жаккард",
        material: "Жаккард",
        price: 0,
        images: [
          "Carter_Rose.jpg",
          "Gloriya-169A-1.jpg",
          "Gloriya-174A-1.jpg",
          "Gloriya-194A-1.jpg",
          "Gloriya-196A-1.jpg",
          "Gloriya-516A-1.jpg",
          "Gloriya-751A-1.jpg",
          "Monstera-Beige_1b.jpg",
          "Monstera-Black_1A.jpg",
          "Neon 12.jpg",
          "Neon 128.jpg",
          "Neon 131.jpg",
          "Rafaello-213-52_3.jpg",
          "Rafaello-P-10043_1.jpg",
          "Rafaello-P-9883_1.jpg",
          "Tokio_133-36_1.jpg",
          "Tokio_144-35_1.jpg",
          "Tokio_144-36_1.jpg",
          "Viola_200A.jpg",
          "Viola_300a.jpg",
          "Viola_400A.jpg",
          "Viola_501A.jpg",
        ],
      },
      {
        name: "Шенилл",
        material: "Шенилл",
        price: 0,
        images: [
          "Akva_110b.jpg",
          "Akva_210a.jpg",
          "Akva_250a.jpg",
          "Akva_370a.jpg",
          "Azaliya_1_5.jpg",
          "Azaliya_2_1.jpg",
          "Azaliya_2_5.jpg",
          "Azaliya_4_5.jpg",
          "Benevento_Jewel.jpg",
          "Benevento_Kornsilk.jpg",
          "Benevento_Moss.jpg",
          "Bryt_white.jpg",
          "Diamond_110C.jpg",
          "Diamond_60C.jpg",
          "Felicia_bordo.jpg",
          "Felicia_green.jpg",
          "Felicia_rose.jpg",
          "Gasmin_16A1.jpg",
          "Gasmin_19A1.jpg",
          "Karolina_15B.jpg",
          "Karolina_16A.jpg",
          "Kelsi_5520_02R.jpg",
          "Kelsi_5520_03R.jpg",
          "Kelsi_5520_05R.jpg",
          "Kelsi_5520_08R.jpg",
          "Kelsi_5520_14R.jpg",
          "Kelsi_5520_66R.jpg",
          "Patricia_200b.jpg",
          "Pozit_Gold.jpg",
          "Pozit_Latte.jpg",
          "Pozit_Mos.jpg",
          "Pozit_Slatte.jpg",
          "Pozitano_bordo.jpg",
          "Shimer_blue.jpg",
          "Shimer_bordo.jpg",
          "Shimer_bronza.jpg",
          "Shimer_payp.jpg",
          "Shimer_salat.jpg",
          "Shimer_strayp.jpg",
          "Siesta_begev.jpg",
          "Siesta_blue.jpg",
          "Silver_Red.jpg",
          "Silver_Stoyn.jpg",
          "Valencia_201C.jpg",
          "Valencia_300B.jpg",
          "Valencia_301B.jpg",
          "Vena white.jpg",
          "Valencia_300C.jpg",
          "Akva_1b.jpg",
          "Аkva_1a.jpg",
        ],
      },
      {
        name: "Экокожа",
        material: "Экокожа",
        price: 0,
        backgroundSize: "cover",
        images: [
          "Madras_0515_G.jpg",
          "Madras_1010_Y_20_R.jpg",
          "Madras_1515_Y_40_R.jpg",
          "Madras_20_20_Y50R.jpg",
          "Madras_20_50_Y_20_R.jpg",
          "Madras_6030_R_10_B.jpg",
          "Madras_60_30_70.jpg",
          "Madras_66Q_RED.jpg",
          "Madras_8020_B_90_G.jpg",
          "Madras_8500_N.jpg",
        ],
      },
    ],
  },

  {
    name: "Амадей 2506",
    categories: [
      {
        images: [
          "Misk 01.jpg",
          "Misk 02.jpg",
          "Ниагара А-8.jpg",
          "Саванна 119.jpg",
          "Саванна 124.jpg",
        ],
      },
    ],
  },

  {
    name: "БоссаНова",
    categories: [
      {
        count: 88,
        skip: [43, 79],
      },
    ],
  },

  {
    name: "Е1",
    categories: [
      {
        backgroundSize: "cover",
        images: [
          "Улица.jpg",
          "Сакура.jpg",
          "Орхидея Белая.jpg",
          "Ночной Лондон.jpg",
          "Париж.jpg",
        ],
      },
    ],
  },

  {
    name: "Кавелио",
    categories: [
      {
        name: "Шенилл",
        material: "Шенилл",
        count: 39,
      },
      {
        name: "Экокожа",
        material: "Экокожа",
        count: 22,
      },
    ],
  },

  {
    name: "ТКП",
    categories: [
      {
        backgroundSize: "cover",
        images: [
          "1.jpg",
          "2А.jpg",
          "2Б.jpg",
          "3.jpg",
          "4.jpg",
          "5.jpg",
          "6.jpg",
          "7.jpg",
          "8А.jpg",
          "8Б.jpg",
          "9.jpg",
          "10.jpg",
          "11.jpg",
          "12.jpg",
        ],
      },
    ],
  },

  {
    name: "ТКП-стул-СМ",
    categories: [
      {
        name: "А",
        count: 26,
      },
      {
        name: "А+",
        count: 15,
      },
      {
        name: "Базовый",
        count: 38,
      },
      {
        name: "Кожзам",
        count: 3,
      },
      {
        name: "Люкс",
        count: 6,
      },
    ],
  },

  {
    name: "Натур Мебель",
    categories: [
      {
        name: "Malta",
        images: [
          "malta_01А.jpg",
          "malta_03А.jpg",
          "malta_15А_.jpg",
          "malta_17.jpg",
        ],
      },
      {
        name: "Falcone",
        images: [
          "falcone_brown.jpg",
          "falcone_cobalt.jpg",
          "falcone_lime.jpg",
          "falcone_purple.jpg",
        ],
      },
      {
        name: "Montana",
        images: [
          "montana-100.jpg",
          "montana-501.jpg",
          "montana-600.jpg",
          "montana-602.jpg",
          "montana-802.jpg",
          "montana-804.jpg",
          "montana-902.jpg",
          "montana-904.jpg",
        ],
      },
      {
        name: "Verona",
        images: [
          "verona_antrazite_grey.jpg",
          "verona_apple_green.jpg",
          "verona_brown.jpg",
          "verona_cyklam.jpg",
          "verona_denim_blue.jpg",
          "verona_light_grey.jpg",
          "verona_vanilla.jpg",
          "verona_wenge.jpg",
        ],
      },
      {
        name: "Экокожа",
        images: [
          "antic_crocodile.jpg",
          "dundi_108.jpg",
          "dundi_109.jpg",
          "dundi_112.jpg",
          "mango_002.jpg",
          "oregon_perlamutr_106.jpg",
          "oregon_perlamutr_120.jpg",
          "polaris_beige.jpg",
          "vegas_light_black.jpg",
          "vegas_lite_amber.jpg",
        ],
      },
    ],
  },

  {
    name: "Шале",
    categories: [
      {
        backgroundSize: "cover",
        images: [
          "astrum-brown.jpg",
          "astrum-honey.jpg",
          "averno-caramel.jpg",
          "averno-chocolate.jpg",
          "charm-pebble.jpg",
          "kalahari-desert.jpg",
          "mercan-ivory.jpg",
          "mercan-java.jpg",
          "mercury-brown.jpg",
          "paisley-berry.jpg",
          "rossi-beige.jpg",
          "rossi-bitter.jpg",
          "rossi-desert-1.jpg",
          "taurus-desert.jpg",
          "vital-chocolate.jpg",
          "persiya-12a.jpg",
          "persiya-12v.jpg",
          "persiya-12s.jpg",
          "persiya-1a.jpg",
          "persiya-1v.jpg",
          "persiya-1s.jpg",
          "persiya-5a.jpg",
          "persiya-5v.jpg",
          "persiya-5s.jpg",
        ],
      },
    ],
  },
]
