export const PRODUCT_KEYWORDS = [
  "банкетка",
  "буфет",
  "комод",
  "пуф",
  "шкаф",
  "стеллаж",
  "стол",
  "столик",
  "стул",
  "табурет",
  "телефон",
  "кресло",
]

export const KEYWORDS = {
  "Банкетки": "/catalog/mebel/banketka",
  "Буфеты": "/catalog/mebel/bufet",
  "Детские кровати": "/catalog/mebel/detskaya_krovat?Тип=Детская кровать",
  "Детские кровати | Двухярусные":
    "/catalog/mebel/detskaya_krovat?Тип=Двухъярусная",
  "Диваны": "/catalog/mebel/divan",
  "Этажерки": "/catalog/mebel/etajerka",
  "Комоды": "/catalog/mebel/komod",
  "Кресла | Компьютерные": "/catalog/mebel/kreslo?Тип=Компьютерное",
  "Кресла | Офисные": "/catalog/mebel/kreslo?Тип=Офисное",
  "Кресла | Вращающиеся": "/catalog/mebel/kreslo?Тип=Вращающееся",
  "Кресла-качалки": "/catalog/mebel/kreslo_kachalka",
  "Кресла-мешки": "/catalog/mebel/kreslo_meshok",
  "Кровати | Двухспальные": "/catalog/mebel/krovat?Внешний вид=Двухспальная",
  "Кровати | Односпальные": "/catalog/mebel/krovat?Внешний вид=Односпальная",
  "Кровати | Подъемные": "/catalog/mebel/krovat?Внешний вид=Подъёмная кровать",
  "Кровати | Полуторные": "/catalog/mebel/krovat?Внешний вид=Полуторная",
  "Кровати | Двухярусные": "/catalog/mebel/krovat?Внешний вид=Двухярусная",
  "Кровати-чердаки": "/catalog/mebel/detskaya_krovat?Тип=Кровать-чердак",
  "Кушетки": "/catalog/mebel/kushetka",
  "Подставки": "/catalog/mebel/podstavka",
  "Полки | Настенные": "/catalog/mebel/polka?Установка=Настенная",
  "Полки | Напольные": "/catalog/mebel/polka?Установка=Напольная",
  "Полки | Подвесные": "/catalog/mebel/polka?Установка=Подвесная",

  "Прихожие | Настенные": "/catalog/mebel/prihojaya?Тип=Настенная",
  "Прихожие | Напольные": "/catalog/mebel/prihojaya?Тип=Напольная",
  "Прихожие | Угловые": "/catalog/mebel/prihojaya?Тип=Угловая",
  "Пуфы": "/catalog/mebel/puf",
  "Раскладушки": "/catalog/mebel/raskladushka",
  "Шкафы | Для одежды": "/catalog/mebel/shkaf?Тип=Для одежды",
  "Шкафы | Для белья": "/catalog/mebel/shkaf?Тип=Для белья",
  "Шкафы | Многофункциональные": "/catalog/mebel/shkaf?Тип=Многофункциональный",
  "Шкафы | Комбинированные": "/catalog/mebel/shkaf?Тип=Комбинированный",
  "Шкафы | Угловые": "/catalog/mebel/shkaf?Тип=Угловой",
  "Шкафы | Книжные": "/catalog/mebel/shkaf?Тип=Книжный",
  "Софы": "/catalog/mebel/sofa",
  "Стеллажи": "/catalog/mebel/stelaj",
  "Стенки | Для одежды": "/catalog/mebel/stenka?Тип=Для одежды",
  "Стенки | Для белья": "/catalog/mebel/stenka?Тип=Для белья",
  "Стенки | Книжные": "/catalog/mebel/stenka?Тип=Книжный",

  "Столы | Обеденные": "/catalog/mebel/stol?Тип=Обеденный",
  "Столы | Кухонные": "/catalog/mebel/stol?Тип=Кухонный",
  "Столы | Письменные": "/catalog/mebel/stol?Тип=Письменный",
  "Столы | Журнальные": "/catalog/mebel/stol?Тип=Журнальный",
  "Столы | Офисные": "/catalog/mebel/stol?Тип=Офисный",
  "Столы | Консольные": "/catalog/mebel/stol?Тип=Консольный",
  "Столы | Кофейные": "/catalog/mebel/stol?Тип=Кофейный",
  "Столы | Чайные": "/catalog/mebel/stol?Тип=Чайный",
  "Столы | Сервировочные": "/catalog/mebel/stol?Тип=Сервировочный",
  "Стулья": "/catalog/mebel/stul",
  "Табуреты": "/catalog/mebel/taburet",
  "Тахты": "/catalog/mebel/tahta",
  "Туалетные столики": "/catalog/mebel/tualetniy_stolik",
  "Тумбы | Прикроватные": "/catalog/mebel/tumba?Тип=Прикроватная",
  "Тумбы | ТВ-тумбы": "/catalog/mebel/tumba?Тип=ТВ тумба",
  "Тумбы | Обувницы": "/catalog/mebel/tumba?Тип=Обувница",
  "Тумбы | Сундуки": "/catalog/mebel/tumba?Тип=Сундук",

  "Вешалки | Настенные": "/catalog/mebel/veshalka?Тип=Настенная",
  "Вешалки | Напольные": "/catalog/mebel/veshalka?Тип=Напольная",
  "Вешалки | Костюмные": "/catalog/mebel/veshalka?Тип=Костюмная",

  "Витрины | Для одежды": "/catalog/mebel/vitrina?Тип=Для одежды",
  "Витрины | Для белья": "/catalog/mebel/vitrina?Тип=Для белья",
  "Витрины | Книжные": "/catalog/mebel/vitrina?Тип=Книжный",
  "Винные шкафы": "/catalog/mebel/winniy_shkaf",
  "Зеркала | Напольные": "/catalog/mebel/zerkalo?Установка=Напольная",
  "Зеркала | Настенные": "/catalog/mebel/zerkalo?Установка=Настенная",
  "Зеркала | Навесные": "/catalog/mebel/zerkalo?Установка=Навесная",
}
